title: Andrew Monty
logo: /assets/logo.svg
email: andrew1503@gmail.com
description: Personal website for web designer/developer Andrew Monty.
baseurl: ""
url: "https://andrewmonty.website"
github_username: AndrewMonty

markdown: kramdown

collections:

excerpt_separator: <!--more-->

plugins:
  - jekyll-postcss

postcss:
  cache: false

include: ["node_modules/tailwindcss","node_modules/@tailwindcss"]
