# Site settings
title: Andrew Monty
logo: /assets/logo.svg
email: andrew1503@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal website for web designer/developer Andrew Monty.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://andrewmonty.website" # the base hostname & protocol for your site
github_username:  AndrewMonty

# Build settings
markdown: kramdown

collections:
- sections

excerpt_separator: <!--more-->