title: Andrew Monty
logo: /assets/logo.svg
email: andrew1503@gmail.com
description: Personal website for web designer/developer Andrew Monty.
baseurl: ""
url: "http://andrewmonty.website"
github_username: AndrewMonty

markdown: kramdown

collections:

excerpt_separator: <!--more-->

plugins:
  - jekyll-postcss

postcss:
  cache: false

sass:
  load_paths:
    - _sass
    - node_modules

include: ["node_modules/tailwindcss"]
